package com.monevo.common.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

	INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
	VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
	NOT_FOUND(HttpStatus.NOT_FOUND),
	METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
	CONCURRENT_MODIFICATION(HttpStatus.CONFLICT),
	RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),

	UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
	TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
	TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
	AUTH_USER_NOT_PROVISIONED(HttpStatus.UNAUTHORIZED),
	FORBIDDEN(HttpStatus.FORBIDDEN),
	ADMIN_REQUIRED(HttpStatus.FORBIDDEN),

	EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
	USER_PENDING_APPROVAL(HttpStatus.FORBIDDEN),
	USER_REJECTED(HttpStatus.FORBIDDEN),
	USER_SUSPENDED(HttpStatus.FORBIDDEN),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND),
	USER_ALREADY_PROCESSED(HttpStatus.CONFLICT),
	CANNOT_MODIFY_SELF(HttpStatus.CONFLICT),

	LEDGER_NOT_FOUND(HttpStatus.NOT_FOUND),
	LEDGER_NOT_MEMBER(HttpStatus.FORBIDDEN),
	LEDGER_OWNER_REQUIRED(HttpStatus.FORBIDDEN),
	LEDGER_CURRENCY_CONFIRM_REQUIRED(HttpStatus.BAD_REQUEST),
	LEDGER_OWNER_CANNOT_LEAVE(HttpStatus.CONFLICT),
	LEDGER_SINGLE_OWNER_VIOLATION(HttpStatus.CONFLICT),

	INVITE_NOT_FOUND(HttpStatus.NOT_FOUND),
	INVITE_EXPIRED(HttpStatus.GONE),
	INVITE_REVOKED(HttpStatus.GONE),
	INVITE_EXHAUSTED(HttpStatus.CONFLICT),
	INVITE_ALREADY_MEMBER(HttpStatus.CONFLICT),
	INVITE_CODE_DUPLICATED(HttpStatus.CONFLICT),

	ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND),
	ACCOUNT_NOT_ACCESSIBLE(HttpStatus.FORBIDDEN),
	ACCOUNT_NAME_DUPLICATED(HttpStatus.CONFLICT),
	ACCOUNT_ARCHIVED(HttpStatus.CONFLICT),
	ACCOUNT_HAS_TRANSACTIONS(HttpStatus.CONFLICT),
	ACCOUNT_SHARE_TARGET_INVALID(HttpStatus.BAD_REQUEST),
	ACCOUNT_NATURE_INVALID(HttpStatus.BAD_REQUEST),
	OPENING_BALANCE_ALREADY_SET(HttpStatus.CONFLICT),

	CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND),
	CATEGORY_DEPTH_EXCEEDED(HttpStatus.BAD_REQUEST),
	CATEGORY_KIND_MISMATCH(HttpStatus.BAD_REQUEST),
	CATEGORY_NOT_LEAF(HttpStatus.BAD_REQUEST),
	CATEGORY_NAME_DUPLICATED(HttpStatus.CONFLICT),
	CATEGORY_HAS_CHILDREN(HttpStatus.CONFLICT),
	CATEGORY_HAS_TRANSACTIONS(HttpStatus.CONFLICT),
	CATEGORY_LEDGER_MISMATCH(HttpStatus.BAD_REQUEST),

	JOURNAL_ENTRY_NOT_FOUND(HttpStatus.NOT_FOUND),
	JOURNAL_ENTRY_UNBALANCED(HttpStatus.BAD_REQUEST),
	JOURNAL_ENTRY_SHAPE_INVALID(HttpStatus.BAD_REQUEST),
	JOURNAL_LINE_ACCOUNT_INVALID(HttpStatus.BAD_REQUEST),
	JOURNAL_LINE_DUPLICATE_ACCOUNT(HttpStatus.BAD_REQUEST),
	TRANSACTION_CURRENCY_MISMATCH(HttpStatus.BAD_REQUEST),
	TRANSACTION_AMOUNT_INVALID(HttpStatus.BAD_REQUEST),
	TRANSACTION_IDEMPOTENCY_KEY_REUSED(HttpStatus.CONFLICT),

	FX_RATE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
	FX_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
	FX_RATE_INVALID(HttpStatus.BAD_REQUEST),
	CURRENCY_NOT_SUPPORTED(HttpStatus.BAD_REQUEST);

	private final HttpStatus status;

	ErrorCode(HttpStatus status) {
		this.status = status;
	}

	public HttpStatus status() {
		return status;
	}
}
