export const errorCodeStatus = {
	INTERNAL_ERROR: 500,
	VALIDATION_FAILED: 400,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	CONCURRENT_MODIFICATION: 409,
	RATE_LIMITED: 429,

	UNAUTHENTICATED: 401,
	TOKEN_EXPIRED: 401,
	TOKEN_INVALID: 401,
	AUTH_USER_NOT_PROVISIONED: 401,
	FORBIDDEN: 403,
	ADMIN_REQUIRED: 403,

	EMAIL_ALREADY_EXISTS: 409,
	USER_PENDING_APPROVAL: 403,
	USER_REJECTED: 403,
	USER_SUSPENDED: 403,
	USER_NOT_FOUND: 404,
	USER_ALREADY_PROCESSED: 409,
	CANNOT_MODIFY_SELF: 409,

	LEDGER_NOT_FOUND: 404,
	LEDGER_NOT_MEMBER: 403,
	LEDGER_OWNER_REQUIRED: 403,
	LEDGER_CURRENCY_CONFIRM_REQUIRED: 400,
	LEDGER_OWNER_CANNOT_LEAVE: 409,
	LEDGER_SINGLE_OWNER_VIOLATION: 409,

	INVITE_NOT_FOUND: 404,
	INVITE_EXPIRED: 410,
	INVITE_REVOKED: 410,
	INVITE_EXHAUSTED: 409,
	INVITE_ALREADY_MEMBER: 409,
	INVITE_CODE_DUPLICATED: 409,

	ACCOUNT_NOT_FOUND: 404,
	ACCOUNT_NOT_ACCESSIBLE: 403,
	ACCOUNT_NAME_DUPLICATED: 409,
	ACCOUNT_ARCHIVED: 409,
	ACCOUNT_HAS_TRANSACTIONS: 409,
	ACCOUNT_SHARE_TARGET_INVALID: 400,
	ACCOUNT_NATURE_INVALID: 400,
	OPENING_BALANCE_ALREADY_SET: 409,

	CATEGORY_NOT_FOUND: 404,
	CATEGORY_DEPTH_EXCEEDED: 400,
	CATEGORY_KIND_MISMATCH: 400,
	CATEGORY_NOT_LEAF: 400,
	CATEGORY_NAME_DUPLICATED: 409,
	CATEGORY_HAS_CHILDREN: 409,
	CATEGORY_HAS_TRANSACTIONS: 409,
	CATEGORY_LEDGER_MISMATCH: 400,

	JOURNAL_ENTRY_NOT_FOUND: 404,
	JOURNAL_ENTRY_UNBALANCED: 400,
	JOURNAL_ENTRY_SHAPE_INVALID: 400,
	JOURNAL_LINE_ACCOUNT_INVALID: 400,
	JOURNAL_LINE_DUPLICATE_ACCOUNT: 400,
	TRANSACTION_CURRENCY_MISMATCH: 400,
	TRANSACTION_AMOUNT_INVALID: 400,
	TRANSACTION_IDEMPOTENCY_KEY_REUSED: 409,

	FX_RATE_UNAVAILABLE: 503,
	FX_SERVICE_UNAVAILABLE: 503,
	FX_RATE_INVALID: 400,
	CURRENCY_NOT_SUPPORTED: 400,
} as const satisfies Record<string, number>;

export type ErrorCode = keyof typeof errorCodeStatus;

export function statusOf(code: ErrorCode): number {
	return errorCodeStatus[code];
}
